sudo: false
language: node_js
node_js:
- 6.5.0
script:
- gem install scss_lint -v 0.49.0
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: KxP+fsA7PMmmoS+/F+8Sg0U7EZR0C2y4/QK4PL5XvgYqjesqWhA6VXBfh+UC3QjXozLEHHgIcknYpypnTHoR/yHISDS2yUj9rcYhuwa1qTYzuTuFrgWAAAXUVfe0tuCLqMIAOprUMAzKCkExpimgTbotiSbH25ZsPof4iDB8e3ItSO1dJ9khakFswCBCzrBeBMZBKByANBlk2NvKvZnsnem+gjcRgHwDROfIgeqWhZxlgrULHkRGaAS1+/7UzHg6fM5VzB3e8s+v+AVOU+Td89M2M75ec2PtE0rxPzpJzTszUR4qGFpa3ofWXc4h0pVMTx6iwklTEw+W84FiFKI2ce2nhMzavJplvM/YNvaj7t/LGd6rR+Vqp3wOb5WHaZ6dvul8388PCk7OEKynN9tZe0KdgfA5T2cCL7SvJwwygmmnbWc7acUBYivl9wOFE6gY/QNXZ7jtMKbagrDQsggMP2aVQNrAsLkXHAm0JhZRjOfaaERrFLhaXHzlJEzJ4vClDVzBiBw0XzYKkjHCK6d9ZEtZNhM5GIA0sbf39HMtM3+blllpgOakY+/NgvTtDymCLcxNj4TfQDEPnJV8oMzT5pm9Av1fv79z9b3T4bUKkOJa7pQo1y281sL98MyRwOqtSxPJpsFodZFAKJJGTKerQA+1d6+d/KY/8DAh1v491js=
